### ISSUE TITLE
Table Height in DropUpMenu

### ISSUE THREAD

**Issue by KoD4K** [teambition/DropdownMenu#10]
I init dropUpMenu. After that try to change rowHeight. But Table height don't change. I try to change tableViewHeight and it also don't help. 
I see in source that I have to see less tableView after change tableViewHeight but it doesn't work. 
Could you help me with this?

P.S. How I change it in your source to rowHeight I need.

**Comment by suricforever** [comment]
new version 2.5.2 for fixing bug
