### ISSUE TITLE
Can I update it's datasource while it is shown?

### ISSUE THREAD

**Issue by angelen10** [teambition/DropdownMenu#12]
When I show the dropdownMenu, I put a searchBar at the top of the DropdownMenu.tableView, after I search, the `items` may be less, how can I update the datasource?

![](https://ww3.sinaimg.cn/large/006tKfTcgy1fivznplnt9j319a0u411g.jpg)

**Comment by suricforever** [comment]
Still can not

**Comment by angelen10** [comment]
Thanks for that. 🙃

**Comment by suricforever** [comment]
Maybe you can custom it, and send me a PR

**Comment by angelen10** [comment]
I'll try it. 😉
