### ISSUE TITLE
Displacement menu after change interface orientation to landscape on the iPad

### ISSUE THREAD

**Issue by AktuBuct** [teambition/DropdownMenu#7]
The bug exist If menu is open on portrait and user change orientation. If menu was close bug not exist.

Fix it please!

**Comment by suricforever** [comment]
Fixed, Test on iPad Pro, iPad  Air, iPad retina

**Comment by AktuBuct** [comment]
Upload it to cocoa pods please

**Comment by suricforever** [comment]
Done

**Comment by suricforever** [comment]
Fixed , version 2.5.1

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by suricforever** [comment]
I will fix it this week

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AktuBuct** [comment]
Thank you so mach. Fix please new issue.
Open access to sections property #8
Many property doesn’t have setters, and after changing it do nothing

**Comment by suricforever** [comment]
I am very busy this week，Maybe you can send me a PR

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
